# Quantum Feature Selection

Feature selection posed as an Ising type of problem can be tackled by many different options. As it was mentioned in the documentation, the idea is to define each feature importance as its importance and the quadratic relation weight as the redundancy between different pairs available.

![featureselection.png](../../assets/featureselection.png)

This what Falcondale builds and then offers different options to solve it.

In [1]:
from sklearn import datasets

# import some data to play with
X, y = datasets.load_breast_cancer(return_X_y=True, as_frame=True)
X

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [2]:
from falcondale import Project

dataset = X.copy()
dataset["target"] = y

myproject = Project(dataset, target="target")
myproject.preprocess()

By default, **Simulated Annealing** will be the technique chose to select our feature subset.

In [3]:
features = myproject.feature_selection(max_cols=10)
features

['mean radius',
 'mean perimeter',
 'mean area',
 'mean compactness',
 'mean concavity',
 'mean symmetry',
 'radius error',
 'perimeter error',
 'concave points error',
 'worst perimeter']

In [4]:
myproject.show_features()

,mean radius,mean perimeter,mean area,mean compactness,mean concavity,mean symmetry,radius error,perimeter error,concave points error,worst perimeter
0,0.521037,0.545989,0.363733,0.792037,0.703140,0.686364,0.356147,0.369034,0.300625,0.668310
1,0.643144,0.615783,0.501591,0.181768,0.203608,0.379798,0.156437,0.124440,0.253836,0.539818
2,0.601496,0.595743,0.449417,0.431017,0.462512,0.509596,0.229622,0.180370,0.389847,0.508442
3,0.210090,0.233501,0.102906,0.811361,0.565604,0.776263,0.139091,0.126655,0.353665,0.241347
4,0.629893,0.630986,0.489290,0.347893,0.463918,0.378283,0.233822,0.220563,0.357075,0.506948
...,...,...,...,...,...,...,...,...,...,...
564,0.690000,0.678668,0.566490,0.296055,0.571462,0.336364,0.385479,0.325873,0.464861,0.576174
565,0.622320,0.604036,0.474019,0.257714,0.337395,0.349495,0.236828,0.209490,0.317863,0.520892
566,0.455251,0.445788,0.303118,0.254340,0.216753,0.267677,0.124896,0.125713,0.294942,0.379949
567,0.644564,0.665538,0.475716,0.790197,0.823336,0.675253,0.222524,0.236300,0.315211,0.668310
568,0.036869,0.028540,0.015907,0.074351,0.000000,0.266162,0.099294,0.084390,0.000000,0.043578

We can try to train a model and check how it would end up being with this selection.

In [5]:
model = myproject.evaluate("qnn")
model.print_report()

              precision    recall  f1-score   support

           0       0.88      0.67      0.76        64
           1       0.83      0.94      0.88       107

    accuracy                           0.84       171
   macro avg       0.85      0.81      0.82       171
weighted avg       0.85      0.84      0.84       171

In [6]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=10, method="sb")
features

['mean radius',
 'mean concavity',
 'mean symmetry',
 'mean fractal dimension',
 'concave points error',
 'worst radius',
 'worst perimeter',
 'worst smoothness',
 'worst concave points',
 'worst symmetry']

Both methods tackle the very same QUBO, so they tend to agree on easy cases. Let's make it harder by reducing the number of features further.

In [7]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sb")
features

['mean fractal dimension', 'worst radius', 'worst concave points']

In [8]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sa")
features

['radius error', 'area error', 'worst texture']

Both solvers are forced to pick exactly the requested number of features thanks to the penalty term in the QUBO, but the selected subsets may differ. Let's check their performance when training a model.

In [9]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sb")
model = myproject.evaluate("qsvc")
model.print_report()

              precision    recall  f1-score   support

           0       0.92      0.84      0.88        64
           1       0.91      0.95      0.93       107

    accuracy                           0.91       171
   macro avg       0.91      0.90      0.90       171
weighted avg       0.91      0.91      0.91       171

In [10]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sa")
model = myproject.evaluate("qsvc")
model.print_report()

              precision    recall  f1-score   support

           0       0.93      0.84      0.89        64
           1       0.91      0.96      0.94       107

    accuracy                           0.92       171
   macro avg       0.92      0.90      0.91       171
weighted avg       0.92      0.92      0.92       171

Finally, **Quantum Approximate Optimization Algorithm** can also be used, in this case we need to take into account that being locally simulated we might be restricted by our machine capacity so we may need to do a pre-selection to decrease the original size of the dataset.

A warning will appear when a previous subset selection is already in force.

In [11]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=12)
features = myproject.feature_selection(max_cols=3, method="qaoa")
model = myproject.evaluate("qsvc")
model.print_report()

              precision    recall  f1-score   support

           0       0.91      0.81      0.86        64
           1       0.89      0.95      0.92       107

    accuracy                           0.90       171
   macro avg       0.90      0.88      0.89       171
weighted avg       0.90      0.90      0.90       171