# Quantum Feature Selection

Feature selection posed as an Ising type of problem can be tackled by many different options. As it was mentioned in the documentation, the idea is to define each feature importance as its importance and the quadratic relation weight as the redundancy between different pairs available.

![featureselection.png](../../assets/featureselection.png)

This what Falcondale builds and then offers different options to solve it.

In [1]:
from sklearn import datasets

# import some data to play with
X, y = datasets.load_breast_cancer(return_X_y=True, as_frame=True)
X

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [2]:
from falcondale import Project

dataset = X.copy()
dataset["target"] = y

myproject = Project(dataset, target="target")
myproject.preprocess()

By default, **Simulated Annealing** will be the technique chose to select our feature subset.

In [3]:
features = myproject.feature_selection(max_cols=10)
features

['mean texture',
 'mean perimeter',
 'mean concave points',
 'radius error',
 'texture error',
 'worst area',
 'worst smoothness',
 'worst concavity',
 'worst concave points',
 'worst symmetry']

In [4]:
myproject.show_features()

,mean texture,mean perimeter,mean concave points,radius error,texture error,worst area,worst smoothness,worst concavity,worst concave points,worst symmetry
0,0.022658,0.545989,0.731113,0.356147,0.120469,0.450698,0.601136,0.568610,0.912027,0.598462
1,0.272574,0.615783,0.348757,0.156437,0.082589,0.435214,0.347553,0.192971,0.639175,0.233590
2,0.390260,0.595743,0.635686,0.229622,0.094303,0.374508,0.483590,0.359744,0.835052,0.403706
3,0.360839,0.233501,0.522863,0.139091,0.175875,0.094008,0.915472,0.548642,0.884880,1.000000
4,0.156578,0.630986,0.518390,0.233822,0.093065,0.341575,0.437364,0.319489,0.558419,0.157500
...,...,...,...,...,...,...,...,...,...,...
564,0.428813,0.678668,0.690358,0.385479,0.197976,0.452664,0.461137,0.328035,0.761512,0.097575
565,0.626987,0.604036,0.486630,0.236828,0.464728,0.379915,0.300007,0.256789,0.559450,0.198502
566,0.621238,0.445788,0.263519,0.124896,0.157974,0.230731,0.282177,0.271805,0.487285,0.128721
567,0.663510,0.665538,0.755467,0.222524,0.272896,0.402035,0.619626,0.749760,0.910653,0.497142
568,0.501522,0.028540,0.000000,0.099294,0.235988,0.020497,0.124084,0.000000,0.000000,0.257441

We can try to train a model and check how it would end up being with this selection.

In [5]:
model = myproject.evaluate("qnn")
model.print_report()

              precision    recall  f1-score   support

           0       0.82      0.72      0.77        64
           1       0.84      0.91      0.87       107

    accuracy                           0.84       171
   macro avg       0.83      0.81      0.82       171
weighted avg       0.84      0.84      0.83       171

In [6]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=10, method="sb")
features

/home/iraitz/Documentos/Falcondale/falcondale-sdk/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

['mean texture',
 'mean concave points',
 'mean symmetry',
 'area error',
 'smoothness error',
 'worst radius',
 'worst perimeter',
 'worst smoothness',
 'worst concavity',
 'worst concave points']

Both methods tackle the very same QUBO, so they tend to agree on easy cases. Let's make it harder by reducing the number of features further.

In [7]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sb")
features

['mean concave points', 'worst texture', 'worst area']

In [8]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sa")
features

['mean concave points', 'area error', 'worst texture']

Both solvers are forced to pick exactly the requested number of features thanks to the penalty term in the QUBO, but the selected subsets may differ. Let's check their performance when training a model.

In [9]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sb")
model = myproject.evaluate("qsvc")
model.print_report()

              precision    recall  f1-score   support

           0       0.97      0.88      0.92        64
           1       0.93      0.98      0.95       107

    accuracy                           0.94       171
   macro avg       0.95      0.93      0.94       171
weighted avg       0.94      0.94      0.94       171

In [10]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="sa")
model = myproject.evaluate("qsvc")
model.print_report()

              precision    recall  f1-score   support

           0       0.95      0.86      0.90        64
           1       0.92      0.97      0.95       107

    accuracy                           0.93       171
   macro avg       0.93      0.92      0.92       171
weighted avg       0.93      0.93      0.93       171

Finally, **Quantum Approximate Optimization Algorithm** can also be used. Being locally simulated we are restricted by our machine capacity, so we need to decrease the size of the problem. The `pool` argument keeps only the most relevant features before building the QUBO.

In [11]:
# Let's set the same starting point
myproject.preprocess()
features = myproject.feature_selection(max_cols=3, method="qaoa", pool=12)
model = myproject.evaluate("qsvc")
model.print_report()

              precision    recall  f1-score   support

           0       0.93      0.81      0.87        64
           1       0.90      0.96      0.93       107

    accuracy                           0.91       171
   macro avg       0.91      0.89      0.90       171
weighted avg       0.91      0.91      0.90       171

Relevance, the mutual information between each feature and the target, is what `pool` uses to rank the features. It can be inspected directly.

In [12]:
from falcondale.feature_selection import relevance

myproject.preprocess()
relevance(myproject.dataset).head(12)

worst perimeter         0.642977
mean concave points     0.614942
worst area              0.609800
worst concave points    0.603460
worst radius            0.602896
mean perimeter          0.527251
mean radius             0.502434
mean concavity          0.499462
mean area               0.498712
area error              0.488229
worst concavity         0.424999
radius error            0.349778
Name: relevance, dtype: float64

With 12 candidates and 3 features to select there are only 220 options, so the **exact** solver can tell us the optimal selection for this QUBO. It is a good reference to check how close the other solvers got.

In [13]:
myproject.preprocess()
myproject.feature_selection(max_cols=3, method="exact", pool=12)

['radius error', 'worst area', 'worst concave points']

By default the QUBO follows the mRMR formulation, where pairs of redundant features are penalized. The previous CMI formulation, rewarding complementary pairs, is still available with `formulation="cmi"`.

In [14]:
myproject.preprocess()
myproject.feature_selection(max_cols=3, method="exact", pool=12, formulation="cmi")

['radius error', 'worst area', 'worst concavity']